server:
  port: 9000
spring:
  datasource:
    url: jdbc:mariadb://localhost:25501/LearnSpringBoot
    username: root
    password: Password7!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update